services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    dns:
     - 8.8.8.8
     - 1.1.1.1
    container_name: ps_app
    env_file:        # <--- ADICIONE ISSO
      - ./web/.env         # <--- ADICIONE ISSO
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./web:/app
    command: npm run dev
    depends_on:
      - db
    networks:
      - ps_network

  db:
    image: postgres:15
    container_name: ps_db
    env_file:
      - .env
    volumes:
      - ./postgresql/pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - ps_network

  proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: ps_proxy
    restart: unless-stopped
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      - ps_network

networks:
  ps_network:
    driver: bridge


